version: '3.3'
services:
  snippetbox-database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'snippetbox'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      
      - '3306:3306'
    expose:
      
      - '3306'
      
    volumes:
      - snippetbox-db:/var/lib/mysql
volumes:
  snippetbox-db: